apiVersion: apps/v1
kind: Deployment
metadata:
  name: unknown300-deployment
  namespace: default
  labels:
    app: unknown300
    role: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: unknown300
  template:
    metadata:
      labels:
        app: unknown300
        role: app
    spec:
      containers:
      - name: unknown300
        image: "localhost:5000/unknown300-deployment"
        imagePullPolicy: Always
        env:
        - name: Redeploy
          value: 
        ports:
            - containerPort: 80
              protocol: TCP
        resources:
          requests:
            cpu: 10m
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0